# Can use _any_ markdown processor; using Jekyll only for parity with zero-config GitHub Pages.

# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/user/project/pages/
image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

## I previously had both `test` and `pages`.  
## TBH don't remember exactly what I was doing with jekyll :-)
## the template in https://gitlab.com/pages/jekyll has only `pages`, so commenting this out for now.
# test:
#   stage: test
#   script:
#     - bundle exec jekyll build -d test
#   artifacts:
#     paths:
#       - test
#   except:
#     - master

pages:
  stage: deploy
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
